grpc:
    port: 14516
    token:
openai:
    base-url:
    api-key:
    model:
nacos:
    enable: true
    client:
        namespace-id: ""
        timeout-ms: 5000
        not-load-cache-at-start: true
        log-dir: "/tmp/nacos/log"
        cache-dir: "/tmp/nacos/cache"
        log-level: "debug"
    server:
        - ip-addr: "localhost"
          port: 8848
          scheme: "http"
          context-path: "/nacos"