version: '3'
services:
    neko-acm:
        container_name: nekoacm
        image: nekoacm
        volumes:
            - ./config.yaml:/app/config.yaml
        ports:
            - 14515:14515
        restart: "always"
