# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Go environment
      uses: actions/setup-go@v5.2.0
      with:
        go-version: '1.23.1'

    - name: Setup Protoc
      uses: arduino/setup-protoc@v3

    - name: Update PATH
      run: export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Tidy
      run: go mod tidy

    - name: Generate
      shell: bash
      run: go generate ./...

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o neko-acm.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: neko-acm
        path: neko-acm.exe
